# Generated by Django 4.0 on 2022-01-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_data',
            name='word',
            field=models.CharField(max_length=1000),
        ),
    ]
